cantoData = [
  {
    "canto": 1,
    "lineStart": 1,
    "lineEnd": 30,
    "circle": -1,
    "shortDescript": "In the Dark Wood",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 1,
    "lineStart": 31,
    "lineEnd": 42,
    "circle": -1,
    "shortDescript": "The Leopard",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 1,
    "lineStart": 43,
    "lineEnd": 60,
    "circle": -1,
    "shortDescript": "The Lion and the She-Wolf",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 1,
    "lineStart": 61,
    "lineEnd": 87,
    "circle": -1,
    "shortDescript": "Virgil",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 1,
    "lineStart": 88,
    "lineEnd": 111,
    "circle": -1,
    "shortDescript": "Virgils Prophecy",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 1,
    "lineStart": 112,
    "lineEnd": 136,
    "circle": -1,
    "shortDescript": "The Journey",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 1,
    "lineEnd": 42,
    "circle": -1,
    "shortDescript": "Dantes Fear",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 43,
    "lineEnd": 57,
    "circle": -1,
    "shortDescript": "Virgil was sent by Beatrice",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 58,
    "lineEnd": 0,
    "circle": -1,
    "shortDescript": "Beatrice's words with Virgil",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 94,
    "lineEnd": 0,
    "circle": -1,
    "shortDescript": "Beartice's words with Lucy",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 115,
    "lineEnd": 0,
    "circle": -1,
    "shortDescript": "Virgil spurs Dante on",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 2,
    "lineStart": 127,
    "lineEnd": 142,
    "circle": -1,
    "shortDescript": "They embark",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 3,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": -1,
    "shortDescript": "At the Gate",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 3,
    "lineStart": 22,
    "lineEnd": 69,
    "circle": 0,
    "shortDescript": "The Neutrals",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Neutrals"
  },
  {
    "canto": 3,
    "lineStart": 70,
    "lineEnd": 81,
    "circle": 0,
    "shortDescript": "Souls at the Banks of Acheron",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 3,
    "lineStart": 82,
    "lineEnd": 99,
    "circle": 0,
    "shortDescript": "Charon",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 3,
    "lineStart": 100,
    "lineEnd": 120,
    "circle": 0,
    "shortDescript": "Charon ferrys the Souls",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 3,
    "lineStart": 121,
    "lineEnd": 136,
    "circle": 0,
    "shortDescript": "Virgil and an Earthquake",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 4,
    "lineStart": 1,
    "lineEnd": 24,
    "circle": 0,
    "shortDescript": "Entering the First Circle",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 4,
    "lineStart": 25,
    "lineEnd": 66,
    "circle": 1,
    "shortDescript": "Souls of Limbo",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 4,
    "lineStart": 67,
    "lineEnd": 78,
    "circle": 1,
    "shortDescript": "The Brighter Ridge of Limbo",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 4,
    "lineStart": 79,
    "lineEnd": 105,
    "circle": 1,
    "shortDescript": "Homer, Horace, Ovid, Lucan",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 4,
    "lineStart": 106,
    "lineEnd": 117,
    "circle": 1,
    "shortDescript": "The Noble Castle",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 4,
    "lineStart": 118,
    "lineEnd": 129,
    "circle": 1,
    "shortDescript": "Unsaved Virtuous: Active Life",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 4,
    "lineStart": 130,
    "lineEnd": 151,
    "circle": 1,
    "shortDescript": "Unsaved Virtuous: Comteplative Life",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 5,
    "lineStart": 1,
    "lineEnd": 24,
    "circle": 2,
    "shortDescript": "Minos",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 5,
    "lineStart": 25,
    "lineEnd": 45,
    "circle": 2,
    "shortDescript": "Souls (The Lustful)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 5,
    "lineStart": 46,
    "lineEnd": 72,
    "circle": 2,
    "shortDescript": "Ladies and Knights of Old",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 5,
    "lineStart": 73,
    "lineEnd": 87,
    "circle": 2,
    "shortDescript": "Francesca and Paolo",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 5,
    "lineStart": 88,
    "lineEnd": 108,
    "circle": 2,
    "shortDescript": "Francesca speaks",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 5,
    "lineStart": 109,
    "lineEnd": 120,
    "circle": 2,
    "shortDescript": "Dante and Virgil's Response",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 5,
    "lineStart": 121,
    "lineEnd": 142,
    "circle": 2,
    "shortDescript": "Francesca's reply",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 6,
    "lineStart": 1,
    "lineEnd": 12,
    "circle": 3,
    "shortDescript": "Dante awakens",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 6,
    "lineStart": 13,
    "lineEnd": 33,
    "circle": 3,
    "shortDescript": "Cerberus",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 6,
    "lineStart": 34,
    "lineEnd": 36,
    "circle": 3,
    "shortDescript": "Souls (The Gluttons)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 6,
    "lineStart": 37,
    "lineEnd": 57,
    "circle": 3,
    "shortDescript": "Ciacco",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 6,
    "lineStart": 58,
    "lineEnd": 76,
    "circle": 3,
    "shortDescript": "Ciacco on Florence",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 6,
    "lineStart": 77,
    "lineEnd": 93,
    "circle": 3,
    "shortDescript": "Ciacco on Townsmen",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 6,
    "lineStart": 94,
    "lineEnd": 115,
    "circle": 3,
    "shortDescript": "Dante and Virgil Continue On",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 7,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 4,
    "shortDescript": "Plutus",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 7,
    "lineStart": 16,
    "lineEnd": 36,
    "circle": 4,
    "shortDescript": "Soul (Avaricious and Prodigal)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 7,
    "lineStart": 37,
    "lineEnd": 66,
    "circle": 4,
    "shortDescript": "Discourse on the Souls",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 7,
    "lineStart": 67,
    "lineEnd": 96,
    "circle": 4,
    "shortDescript": "Virgil on Fortune",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 7,
    "lineStart": 97,
    "lineEnd": 108,
    "circle": 5,
    "shortDescript": "The River Styx",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 7,
    "lineStart": 109,
    "lineEnd": 117,
    "circle": 5,
    "shortDescript": "Souls in the Bog of Styx",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 7,
    "lineStart": 118,
    "lineEnd": 130,
    "circle": 5,
    "shortDescript": "Souls under Styx",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 8,
    "lineStart": 1,
    "lineEnd": 12,
    "circle": 5,
    "shortDescript": "Tower in the distance",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 8,
    "lineStart": 13,
    "lineEnd": 24,
    "circle": 5,
    "shortDescript": "Phlegyas",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 8,
    "lineStart": 25,
    "lineEnd": 30,
    "circle": 5,
    "shortDescript": "Boarding the Skiff",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 8,
    "lineStart": 31,
    "lineEnd": 63,
    "circle": 5,
    "shortDescript": "Flippo Argenti",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 8,
    "lineStart": 64,
    "lineEnd": 81,
    "circle": 5,
    "shortDescript": "Approaching Dis",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 8,
    "lineStart": 82,
    "lineEnd": 93,
    "circle": 6,
    "shortDescript": "The Wall of Dis",
    "motion": 0,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 8,
    "lineStart": 94,
    "lineEnd": 114,
    "circle": 6,
    "shortDescript": "Virgil go to the Fallen Angels",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 8,
    "lineStart": 115,
    "lineEnd": 130,
    "circle": 6,
    "shortDescript": "The Gates to Lower Hell are shut",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 9,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 6,
    "shortDescript": "Outside the Gates",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 9,
    "lineStart": 16,
    "lineEnd": 33,
    "circle": 6,
    "shortDescript": "Virgil's prior journey through Hell",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 9,
    "lineStart": 34,
    "lineEnd": 51,
    "circle": 6,
    "shortDescript": "The Furies",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 9,
    "lineStart": 52,
    "lineEnd": 63,
    "circle": 6,
    "shortDescript": "Medusa may appear",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 9,
    "lineStart": 64,
    "lineEnd": 84,
    "circle": 6,
    "shortDescript": "A Messenger Approaches",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Angel"
  },
  {
    "canto": 9,
    "lineStart": 85,
    "lineEnd": 99,
    "circle": 6,
    "shortDescript": "The Messenger",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Angel"
  },
  {
    "canto": 9,
    "lineStart": 100,
    "lineEnd": 105,
    "circle": 6,
    "shortDescript": "The Messenger departs",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Angel"
  },
  {
    "canto": 9,
    "lineStart": 106,
    "lineEnd": 117,
    "circle": 6,
    "shortDescript": "Entry into Dis",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 9,
    "lineStart": 118,
    "lineEnd": 133,
    "circle": 6,
    "shortDescript": "Souls in Tombs (Heritics)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 10,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": 6,
    "shortDescript": "Dante and Virgil among the Tombs",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 10,
    "lineStart": 22,
    "lineEnd": 51,
    "circle": 6,
    "shortDescript": "Farinata",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 10,
    "lineStart": 52,
    "lineEnd": 72,
    "circle": 6,
    "shortDescript": "Cavalcante (in the same Tomb)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 10,
    "lineStart": 73,
    "lineEnd": 93,
    "circle": 6,
    "shortDescript": "Farinata's family and Florence",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 10,
    "lineStart": 94,
    "lineEnd": 108,
    "circle": 6,
    "shortDescript": "Souls's knowledge of the present",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 10,
    "lineStart": 109,
    "lineEnd": 114,
    "circle": 6,
    "shortDescript": "Dante's apology",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 10,
    "lineStart": 115,
    "lineEnd": 123,
    "circle": 6,
    "shortDescript": "Other Souls in the Tomb",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 10,
    "lineStart": 124,
    "lineEnd": 136,
    "circle": 6,
    "shortDescript": "Toward the Seventh Circle",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 11,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 6,
    "shortDescript": "Tomb of Pope Anastasius",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 11,
    "lineStart": 16,
    "lineEnd": 66,
    "circle": 6,
    "shortDescript": "Virgil on the Lowest Circles",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 11,
    "lineStart": 67,
    "lineEnd": 90,
    "circle": 6,
    "shortDescript": "Virgil on Upper Hell",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 11,
    "lineStart": 91,
    "lineEnd": 115,
    "circle": 6,
    "shortDescript": "Virgil on Usury",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 12,
    "lineStart": 1,
    "lineEnd": 12,
    "circle": 7,
    "shortDescript": "Descent of Sight of the Minotaur",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 12,
    "lineStart": 13,
    "lineEnd": 27,
    "circle": 7,
    "shortDescript": "The Minotaur",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 12,
    "lineStart": 28,
    "lineEnd": 45,
    "circle": 7,
    "shortDescript": "The Rockslide",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 12,
    "lineStart": 46,
    "lineEnd": 54,
    "circle": 7,
    "shortDescript": "Phlegethon (River of Blood)",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 12,
    "lineStart": 55,
    "lineEnd": 66,
    "circle": 7,
    "shortDescript": "The Centaurs",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 12,
    "lineStart": 67,
    "lineEnd": 75,
    "circle": 7,
    "shortDescript": "Nessus, Chiron, Pholus (Centaurs)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 12,
    "lineStart": 76,
    "lineEnd": 90,
    "circle": 7,
    "shortDescript": "Chiron sees Dante is alive",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 12,
    "lineStart": 90,
    "lineEnd": 102,
    "circle": 7,
    "shortDescript": "Nessus assigned to protect them",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 12,
    "lineStart": 103,
    "lineEnd": 114,
    "circle": 7,
    "shortDescript": "Souls in River (Violence to Others)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 12,
    "lineStart": 115,
    "lineEnd": 117,
    "circle": 7,
    "shortDescript": "River up to their heads",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 12,
    "lineStart": 118,
    "lineEnd": 120,
    "circle": 7,
    "shortDescript": "Guy de Montfort",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 12,
    "lineStart": 121,
    "lineEnd": 126,
    "circle": 7,
    "shortDescript": "Crossing on Nessus's back",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 12,
    "lineStart": 127,
    "lineEnd": 139,
    "circle": 7,
    "shortDescript": "Other Souls in the River",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 13,
    "lineStart": 1,
    "lineEnd": 9,
    "circle": 7,
    "shortDescript": "The Forest (Violence to Self)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 13,
    "lineStart": 10,
    "lineEnd": 15,
    "circle": 7,
    "shortDescript": "The Harpies",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 13,
    "lineStart": 16,
    "lineEnd": 30,
    "circle": 7,
    "shortDescript": "Lamentations of the Trees",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 13,
    "lineStart": 31,
    "lineEnd": 54,
    "circle": 7,
    "shortDescript": "Pier delle Vigne",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 13,
    "lineStart": 55,
    "lineEnd": 78,
    "circle": 7,
    "shortDescript": "Pier's oration",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 13,
    "lineStart": 79,
    "lineEnd": 90,
    "circle": 7,
    "shortDescript": "Virgil's questions",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 13,
    "lineStart": 91,
    "lineEnd": 108,
    "circle": 7,
    "shortDescript": "Pier's answers",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 13,
    "lineStart": 109,
    "lineEnd": 123,
    "circle": 7,
    "shortDescript": "The Spendthrifts (Jacopo)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 13,
    "lineStart": 124,
    "lineEnd": 129,
    "circle": 7,
    "shortDescript": "The Dogs",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 13,
    "lineStart": 130,
    "lineEnd": 151,
    "circle": 7,
    "shortDescript": "The Broken Bush",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 14,
    "lineStart": 1,
    "lineEnd": 3,
    "circle": 7,
    "shortDescript": "The Broken Bush",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 14,
    "lineStart": 6,
    "lineEnd": 18,
    "circle": 7,
    "shortDescript": "Crossing to the Third Ring",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 14,
    "lineStart": 19,
    "lineEnd": 42,
    "circle": 7,
    "shortDescript": "The Violent Against God",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 14,
    "lineStart": 43,
    "lineEnd": 60,
    "circle": 7,
    "shortDescript": "Capaneus",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 14,
    "lineStart": 61,
    "lineEnd": 72,
    "circle": 7,
    "shortDescript": "Virgil to Capaneus",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 14,
    "lineStart": 73,
    "lineEnd": 93,
    "circle": 7,
    "shortDescript": "River of blood",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 14,
    "lineStart": 94,
    "lineEnd": 111,
    "circle": 7,
    "shortDescript": "The Old Man of Crete",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 14,
    "lineStart": 112,
    "lineEnd": 135,
    "circle": 7,
    "shortDescript": "The Rivers of Hell",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 14,
    "lineStart": 136,
    "lineEnd": 142,
    "circle": 7,
    "shortDescript": "Lethe",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 15,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 7,
    "shortDescript": "Dante and Virgil Continue On",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 15,
    "lineStart": 16,
    "lineEnd": 21,
    "circle": 7,
    "shortDescript": "Group of Souls",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 15,
    "lineStart": 22,
    "lineEnd": 124,
    "circle": 7,
    "shortDescript": "Brunetto Latini",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 16,
    "lineStart": 1,
    "lineEnd": 27,
    "circle": 7,
    "shortDescript": "Three Souls",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 15,
    "lineStart": 28,
    "lineEnd": 45,
    "circle": 7,
    "shortDescript": "Iacopo Speaks",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 16,
    "lineStart": 46,
    "lineEnd": 63,
    "circle": 7,
    "shortDescript": "Dante's response",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 16,
    "lineStart": 64,
    "lineEnd": 72,
    "circle": 0,
    "shortDescript": "Iacopo's question",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 16,
    "lineStart": 73,
    "lineEnd": 87,
    "circle": 0,
    "shortDescript": "Dante's reply and their parting words",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 16,
    "lineStart": 88,
    "lineEnd": 105,
    "circle": 7,
    "shortDescript": "The Waterfall",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 16,
    "lineStart": 106,
    "lineEnd": 114,
    "circle": 7,
    "shortDescript": "Cord tossed into the abyss",
    "motion": 0,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 16,
    "lineStart": 115,
    "lineEnd": 136,
    "circle": 7,
    "shortDescript": "Awaiting Geryon",
    "motion": 0,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 17,
    "lineStart": 1,
    "lineEnd": 27,
    "circle": 7,
    "shortDescript": "Geryon",
    "motion": 0,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 17,
    "lineStart": 28,
    "lineEnd": 45,
    "circle": 7,
    "shortDescript": "Descent to the Edge",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 17,
    "lineStart": 46,
    "lineEnd": 78,
    "circle": 7,
    "shortDescript": "Souls at the Edge (Usurers)",
    "motion": 0,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 17,
    "lineStart": 79,
    "lineEnd": 90,
    "circle": 7,
    "shortDescript": "Virgil mounted on Geryon",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 17,
    "lineStart": 91,
    "lineEnd": 99,
    "circle": 7,
    "shortDescript": "Dante mounts Geryon",
    "motion": 0,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 17,
    "lineStart": 100,
    "lineEnd": 136,
    "circle": 7,
    "shortDescript": "Descent on Geryon",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 18,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": 8,
    "shortDescript": "Entry to Malebolge",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 18,
    "lineStart": 22,
    "lineEnd": 33,
    "circle": 8.1,
    "shortDescript": "Panderers",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 18,
    "lineStart": 34,
    "lineEnd": 39,
    "circle": 8.1,
    "shortDescript": "Horned Demons",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 18,
    "lineStart": 40,
    "lineEnd": 66,
    "circle": 8.1,
    "shortDescript": "Venedico Caccianemico",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 18,
    "lineStart": 67,
    "lineEnd": 81,
    "circle": 8.1,
    "shortDescript": "Seducers",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 18,
    "lineStart": 82,
    "lineEnd": 99,
    "circle": 8.1,
    "shortDescript": "Jason",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 18,
    "lineStart": 100,
    "lineEnd": 111,
    "circle": 8.2,
    "shortDescript": "Crossing to the Second Ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 18,
    "lineStart": 112,
    "lineEnd": 114,
    "circle": 8.2,
    "shortDescript": "Flatterers",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 18,
    "lineStart": 115,
    "lineEnd": 126,
    "circle": 8.2,
    "shortDescript": "Alessio",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 18,
    "lineStart": 127,
    "lineEnd": 136,
    "circle": 8.2,
    "shortDescript": "Thais",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 19,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": 8.3,
    "shortDescript": "Approacing the Simoniacs",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 19,
    "lineStart": 22,
    "lineEnd": 30,
    "circle": 8.3,
    "shortDescript": "Souls (Simoniacs)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 19,
    "lineStart": 31,
    "lineEnd": 45,
    "circle": 8.3,
    "shortDescript": "Descent into the ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 19,
    "lineStart": 46,
    "lineEnd": 87,
    "circle": 8.3,
    "shortDescript": "Pope Nicholas III",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 19,
    "lineStart": 88,
    "lineEnd": 123,
    "circle": 8.3,
    "shortDescript": "Dante's Invective",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 19,
    "lineStart": 124,
    "lineEnd": 133,
    "circle": 8.3,
    "shortDescript": "Virgil carries Dante to the next ridge",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 20,
    "lineStart": 1,
    "lineEnd": 24,
    "circle": 8.4,
    "shortDescript": "The Diviners",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 20,
    "lineStart": 25,
    "lineEnd": 51,
    "circle": 8.4,
    "shortDescript": "Amphiaraus, Tiresias, Aruns",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 20,
    "lineStart": 52,
    "lineEnd": 105,
    "circle": 8.4,
    "shortDescript": "Manto",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 20,
    "lineStart": 106,
    "lineEnd": 123,
    "circle": 8.4,
    "shortDescript": "Eurypylus, Michael Scot, and others",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 20,
    "lineStart": 124,
    "lineEnd": 130,
    "circle": 8.4,
    "shortDescript": "Time to move on",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 21,
    "lineStart": 1,
    "lineEnd": 6,
    "circle": 8.5,
    "shortDescript": "Arrival in Darkness",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 21,
    "lineStart": 7,
    "lineEnd": 21,
    "circle": 8.5,
    "shortDescript": "The Pitch",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Architecture"
  },
  {
    "canto": 21,
    "lineStart": 22,
    "lineEnd": 33,
    "circle": 8.5,
    "shortDescript": "A Devil (A Malebrache)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 21,
    "lineStart": 34,
    "lineEnd": 45,
    "circle": 8.5,
    "shortDescript": "Sinner thrown in the pitch",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 21,
    "lineStart": 45,
    "lineEnd": 57,
    "circle": 8.5,
    "shortDescript": "The Malebrache",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 21,
    "lineStart": 58,
    "lineEnd": 75,
    "circle": 8.5,
    "shortDescript": "Dante hides, Virgil to the Malebrache",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 21,
    "lineStart": 76,
    "lineEnd": 87,
    "circle": 8.5,
    "shortDescript": "Malcoda (Leader)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 21,
    "lineStart": 88,
    "lineEnd": 105,
    "circle": 8.5,
    "shortDescript": "Dante joins them",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 21,
    "lineStart": 106,
    "lineEnd": 117,
    "circle": 8.5,
    "shortDescript": "Malcoda lies about the bridges",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 21,
    "lineStart": 118,
    "lineEnd": 139,
    "circle": 8.5,
    "shortDescript": "Ten Malebrache escort them",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 22,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 8.5,
    "shortDescript": "Savage Company",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 22,
    "lineStart": 16,
    "lineEnd": 30,
    "circle": 8.5,
    "shortDescript": "Barrators in the pitch",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 22,
    "lineStart": 31,
    "lineEnd": 63,
    "circle": 8.5,
    "shortDescript": "Ciampolo caught out of the pitch",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 22,
    "lineStart": 64,
    "lineEnd": 78,
    "circle": 8.5,
    "shortDescript": "Virgil's questions while Ciampolo is punished",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 22,
    "lineStart": 79,
    "lineEnd": 90,
    "circle": 8.5,
    "shortDescript": "Fra Gomita and Michel Zanche",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 22,
    "lineStart": 91,
    "lineEnd": 117,
    "circle": 8.5,
    "shortDescript": "Ciampolo tricks the Malebrache",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 22,
    "lineStart": 118,
    "lineEnd": 151,
    "circle": 8.5,
    "shortDescript": "Ciampolo dives Malebrache purse",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 23,
    "lineStart": 1,
    "lineEnd": 33,
    "circle": 8.5,
    "shortDescript": "Dante and Virgil leave the Malebranche",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 23,
    "lineStart": 34,
    "lineEnd": 36,
    "circle": 8.5,
    "shortDescript": "Malebranche pursue",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 23,
    "lineStart": 37,
    "lineEnd": 51,
    "circle": 8.5,
    "shortDescript": "Virgil carries Dante to the next ridge",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 23,
    "lineStart": 52,
    "lineEnd": 57,
    "circle": 8.6,
    "shortDescript": "Malebranche stuck above",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 23,
    "lineStart": 58,
    "lineEnd": 75,
    "circle": 8.6,
    "shortDescript": "The Hypocrites",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 23,
    "lineStart": 76,
    "lineEnd": 108,
    "circle": 8.6,
    "shortDescript": "Catalano and Loderingo",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 23,
    "lineStart": 109,
    "lineEnd": 126,
    "circle": 8.6,
    "shortDescript": "Caiaphas nailed underfoot",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 23,
    "lineStart": 127,
    "lineEnd": 144,
    "circle": 8.6,
    "shortDescript": "Virgil learns all the bridges were broken",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 24,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": 8.6,
    "shortDescript": "Virgil trouble, metaphor",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 24,
    "lineStart": 22,
    "lineEnd": 63,
    "circle": 8.6,
    "shortDescript": "Climbing out of the ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 24,
    "lineStart": 64,
    "lineEnd": 81,
    "circle": 8.6,
    "shortDescript": "A voice from the next ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 24,
    "lineStart": 82,
    "lineEnd": 90,
    "circle": 8.7,
    "shortDescript": "Serpents",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 24,
    "lineStart": 91,
    "lineEnd": 96,
    "circle": 8.7,
    "shortDescript": "The Thieves",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 24,
    "lineStart": 97,
    "lineEnd": 120,
    "circle": 8.7,
    "shortDescript": "Vanni Fucci to ashes and back",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 24,
    "lineStart": 121,
    "lineEnd": 151,
    "circle": 8.7,
    "shortDescript": "Dialogue with Vanni",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 25,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 8.7,
    "shortDescript": "Vanni's punishment",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 25,
    "lineStart": 16,
    "lineEnd": 33,
    "circle": 8.7,
    "shortDescript": "Cacus",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 25,
    "lineStart": 34,
    "lineEnd": 48,
    "circle": 8.7,
    "shortDescript": "Transformations of Thieves/Serpents",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 25,
    "lineStart": 49,
    "lineEnd": 78,
    "circle": 8.7,
    "shortDescript": "Angello and Cianfa mutate",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Serpent"
  },
  {
    "canto": 25,
    "lineStart": 79,
    "lineEnd": 141,
    "circle": 8.7,
    "shortDescript": "Buoso and Francesco transmutate",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Serpent"
  },
  {
    "canto": 25,
    "lineStart": 142,
    "lineEnd": 151,
    "circle": 8.7,
    "shortDescript": "Puccio unchanged",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 26,
    "lineStart": 1,
    "lineEnd": 12,
    "circle": 8.7,
    "shortDescript": "Florence in Hell",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 26,
    "lineStart": 13,
    "lineEnd": 18,
    "circle": 8.7,
    "shortDescript": "Climbing out of the ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 26,
    "lineStart": 19,
    "lineEnd": 51,
    "circle": 8.8,
    "shortDescript": "False Consellors (within flames)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 26,
    "lineStart": 52,
    "lineEnd": 75,
    "circle": 8.8,
    "shortDescript": "Ulysses and Diomedes (Double Flame)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 26,
    "lineStart": 76,
    "lineEnd": 84,
    "circle": 8.8,
    "shortDescript": "Virgil to Ulysses and Diomedes",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Virgil"
  },
  {
    "canto": 26,
    "lineStart": 85,
    "lineEnd": 142,
    "circle": 8.8,
    "shortDescript": "Ulysses' tale",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 27,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 8.8,
    "shortDescript": "Another flame appears",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 27,
    "lineStart": 16,
    "lineEnd": 0,
    "circle": 8.8,
    "shortDescript": "Guido da Montefeltro",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 27,
    "lineStart": 34,
    "lineEnd": 57,
    "circle": 8.8,
    "shortDescript": "Dante's response",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 27,
    "lineStart": 58,
    "lineEnd": 129,
    "circle": 8.8,
    "shortDescript": "Guido's story",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 27,
    "lineStart": 130,
    "lineEnd": 136,
    "circle": 8.8,
    "shortDescript": "Guido leaves, they depart",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 28,
    "lineStart": 1,
    "lineEnd": 36,
    "circle": 8.9,
    "shortDescript": "Scismatics",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 28,
    "lineStart": 37,
    "lineEnd": 42,
    "circle": 8.9,
    "shortDescript": "Devil with a Sword",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 28,
    "lineStart": 42,
    "lineEnd": 63,
    "circle": 8.9,
    "shortDescript": "Dante noticed",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 28,
    "lineStart": 64,
    "lineEnd": 93,
    "circle": 8.9,
    "shortDescript": "Pier da Medicina",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 28,
    "lineStart": 94,
    "lineEnd": 102,
    "circle": 8.9,
    "shortDescript": "Curio",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 28,
    "lineStart": 103,
    "lineEnd": 117,
    "circle": 8.9,
    "shortDescript": "Mosca",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 28,
    "lineStart": 118,
    "lineEnd": 142,
    "circle": 8.9,
    "shortDescript": "Betran de Born",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 29,
    "lineStart": 1,
    "lineEnd": 36,
    "circle": 8.9,
    "shortDescript": "Dante lingers",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 29,
    "lineStart": 37,
    "lineEnd": 51,
    "circle": 8.11,
    "shortDescript": "Approaching the last ditch",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 29,
    "lineStart": 52,
    "lineEnd": 72,
    "circle": 8.11,
    "shortDescript": "The Counterfeiters",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 29,
    "lineStart": 73,
    "lineEnd": 99,
    "circle": 8.11,
    "shortDescript": "Griffolino and Capocchio",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 29,
    "lineStart": 100,
    "lineEnd": 123,
    "circle": 8.11,
    "shortDescript": "Griffolino's story",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 29,
    "lineStart": 124,
    "lineEnd": 139,
    "circle": 8.11,
    "shortDescript": "Capocchio's story",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 30,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": 8.11,
    "shortDescript": "Metaphor of fury",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 30,
    "lineStart": 24,
    "lineEnd": 48,
    "circle": 8.11,
    "shortDescript": "Gianni and Myrrha",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 30,
    "lineStart": 49,
    "lineEnd": 90,
    "circle": 8.11,
    "shortDescript": "Master Adam",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 30,
    "lineStart": 91,
    "lineEnd": 99,
    "circle": 8.11,
    "shortDescript": "Potiphar's wife and Sinon",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 30,
    "lineStart": 100,
    "lineEnd": 129,
    "circle": 8.11,
    "shortDescript": "Sinon and Master Adam fight",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 30,
    "lineStart": 130,
    "lineEnd": 148,
    "circle": 8.11,
    "shortDescript": "Dante shamed",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 31,
    "lineStart": 1,
    "lineEnd": 18,
    "circle": 8.11,
    "shortDescript": "Leaving Malebolge",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 31,
    "lineStart": 19,
    "lineEnd": 45,
    "circle": 9,
    "shortDescript": "Giants",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demons"
  },
  {
    "canto": 31,
    "lineStart": 46,
    "lineEnd": 81,
    "circle": 9,
    "shortDescript": "Nimrod",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 31,
    "lineStart": 82,
    "lineEnd": 111,
    "circle": 9,
    "shortDescript": "Ephialtes",
    "motion": 0,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 31,
    "lineStart": 112,
    "lineEnd": 129,
    "circle": 9,
    "shortDescript": "Antaeus",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 31,
    "lineStart": 130,
    "lineEnd": 145,
    "circle": 9,
    "shortDescript": "Antaeus lowers Dante and Virgil",
    "motion": 1,
    "threshold": 1,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 32,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 9,
    "shortDescript": "Apostrophe on Treachery",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 32,
    "lineStart": 16,
    "lineEnd": 30,
    "circle": 9,
    "shortDescript": "A Voice from the Ice",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 32,
    "lineStart": 31,
    "lineEnd": 39,
    "circle": 9,
    "shortDescript": "Traitors of Caina (against kin)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 32,
    "lineStart": 40,
    "lineEnd": 51,
    "circle": 9,
    "shortDescript": "Alessandro and Napoleone",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 32,
    "lineStart": 52,
    "lineEnd": 69,
    "circle": 9,
    "shortDescript": "Camicione de' Parri",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 32,
    "lineStart": 70,
    "lineEnd": 75,
    "circle": 9,
    "shortDescript": "Traitors of Anternora (against party)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 32,
    "lineStart": 76,
    "lineEnd": 105,
    "circle": 9,
    "shortDescript": "Bocca",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 32,
    "lineStart": 106,
    "lineEnd": 108,
    "circle": 9,
    "shortDescript": "Buoso da Duera names Bocca",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 32,
    "lineStart": 109,
    "lineEnd": 123,
    "circle": 9,
    "shortDescript": "Bocca names others",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 32,
    "lineStart": 124,
    "lineEnd": 139,
    "circle": 9,
    "shortDescript": "Ugolino and Ruggieri",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 33,
    "lineStart": 1,
    "lineEnd": 78,
    "circle": 9,
    "shortDescript": "Ugolino's speech",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 33,
    "lineStart": 79,
    "lineEnd": 90,
    "circle": 9,
    "shortDescript": "Apostrophe on Pisa",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 33,
    "lineStart": 91,
    "lineEnd": 99,
    "circle": 9,
    "shortDescript": "Traitors of Ptolomea (against friends)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 33,
    "lineStart": 100,
    "lineEnd": 108,
    "circle": 9,
    "shortDescript": "The Wind",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 33,
    "lineStart": 109,
    "lineEnd": 157,
    "circle": 9,
    "shortDescript": "Fra Albergio",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul"
  },
  {
    "canto": 34,
    "lineStart": 1,
    "lineEnd": 9,
    "circle": 9,
    "shortDescript": "Entry in Judecca",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 34,
    "lineStart": 10,
    "lineEnd": 15,
    "circle": 9,
    "shortDescript": "Traitors of Judecca (against lords)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 34,
    "lineStart": 16,
    "lineEnd": 36,
    "circle": 9,
    "shortDescript": "Lucifer",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 34,
    "lineStart": 37,
    "lineEnd": 45,
    "circle": 9,
    "shortDescript": "Judas, Cassius Brutus",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls"
  },
  {
    "canto": 34,
    "lineStart": 46,
    "lineEnd": 69,
    "circle": 9,
    "shortDescript": "Lucifer's body",
    "motion": 0,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Demon"
  },
  {
    "canto": 34,
    "lineStart": 70,
    "lineEnd": 126,
    "circle": 9,
    "shortDescript": "Exiting the Inferno",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  },
  {
    "canto": 34,
    "lineStart": 127,
    "lineEnd": 139,
    "circle": 9,
    "shortDescript": "Watercourse to Purgatory",
    "motion": 1,
    "threshold": 0,
    "object": 0,
    "speech": 0,
    "objectType": "Dante"
  }
];