eventData = [
  {
    "canto": 1,
    "lineStart": 1,
    "lineEnd": 30,
    "circle": -1,
    "shortDescript": "In the Dark Wood",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture",
    "objectNumber": "multi",
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 1,
    "lineStart": 31,
    "lineEnd": 42,
    "circle": -1,
    "shortDescript": "The Leopard",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 1,
    "lineStart": 43,
    "lineEnd": 60,
    "circle": -1,
    "shortDescript": "The Lion and the She-Wolf",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons",
    "objectNumber": 2,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 1,
    "lineStart": 61,
    "lineEnd": 87,
    "circle": -1,
    "shortDescript": "Virgil",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Virgil",
    "objectNumber": 1,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 3,
    "lineStart": 1,
    "lineEnd": 21,
    "circle": -1,
    "shortDescript": "At the Gate",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture",
    "objectNumber": 1,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 3,
    "lineStart": 22,
    "lineEnd": 69,
    "circle": 0,
    "shortDescript": "The Neutrals",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Neutrals",
    "objectNumber": "m",
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 2,
    "radiusStart": 2,
    "ychange": 0,
    "HSLlightHigh": 0.43,
    "HSLlightLow": 0,
    "HSLsat": 0.06,
    "HSLhue": 0.58,
    "danteTheta": 4.3,
    "thetaSpread": 0.05,
    "thetaStart": 5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.5,
    "dots": 80
  },
  {
    "canto": 3,
    "lineStart": 70,
    "lineEnd": 81,
    "circle": 0,
    "shortDescript": "Souls at the Banks of Acheron",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 3,
    "radiusStart": 6,
    "ychange": 0,
    "HSLlightHigh": 0.5,
    "HSLlightLow": 0.3,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 0.3,
    "thetaStart": 4.45,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 47
  },
  {
    "canto": 3,
    "lineStart": 82,
    "lineEnd": 99,
    "circle": 0,
    "shortDescript": "Charon",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 10,
    "radiusStart": 10,
    "ychange": 0,
    "HSLlightHigh": 0.35,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 4.3,
    "thetaSpread": 0,
    "thetaStart": 4.3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.5,
    "dots": 1
  },
  {
    "canto": 4,
    "lineStart": 25,
    "lineEnd": 66,
    "circle": 1,
    "shortDescript": "Souls of Limbo",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 5,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.8,
    "HSLlightLow": 0.2,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 2.6,
    "thetaStart": 5.7,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 90
  },
  {
    "canto": 4,
    "lineStart": 67,
    "lineEnd": 78,
    "circle": 1,
    "shortDescript": "The Brighter Ridge of Limbo",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 5,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.8,
    "HSLlightLow": 0.05,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 1,
    "thetaStart": 3.1,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 80
  },
  {
    "canto": 4,
    "lineStart": 79,
    "lineEnd": 105,
    "circle": 1,
    "shortDescript": "Homer, Horace, Ovid, Lucan",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 4,
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 2,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.8,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 0.02,
    "thetaStart": 2.1,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 4
  },
  {
    "canto": 4,
    "lineStart": 106,
    "lineEnd": 117,
    "circle": 1,
    "shortDescript": "The Noble Castle",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Architecture",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 5,
    "radiusStart": 5,
    "ychange": 0,
    "HSLlightHigh": 0.32,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.27,
    "danteTheta": 4.3,
    "thetaSpread": 0.02,
    "thetaStart": 2,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 1.2,
    "dots": 1
  },
  {
    "canto": 4,
    "lineStart": 118,
    "lineEnd": 129,
    "circle": 1,
    "shortDescript": "Unsaved Virtuous: Active Life",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 14,
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 1,
    "radiusStart": 6,
    "ychange": 0,
    "HSLlightHigh": 0.65,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 0.02,
    "thetaStart": 1.95,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 14
  },
  {
    "canto": 4,
    "lineStart": 130,
    "lineEnd": 151,
    "circle": 1,
    "shortDescript": "Unsaved Virtuous: Comteplative Life",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 21,
    "distribution": "rows",
    "rows": 3,
    "radiusEnd": 1,
    "radiusStart": 2,
    "ychange": 0,
    "HSLlightHigh": 0.75,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 4.3,
    "thetaSpread": 0.02,
    "thetaStart": 1.95,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 21
  },
  {
    "canto": 5,
    "lineStart": 1,
    "lineEnd": 24,
    "circle": 2,
    "shortDescript": "Minos",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0.3,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 1.5,
    "thetaSpread": 0,
    "thetaStart": 1.5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 1
  },
  {
    "canto": 5,
    "lineStart": 25,
    "lineEnd": 45,
    "circle": 2,
    "shortDescript": "Souls (The Lustful)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 5,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.5,
    "HSLlightLow": 0.2,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 4,
    "thetaStart": 2.5,
    "thetaGapStart": 0.6,
    "thetaGapEnd": 0.2,
    "dotSize": 0.4,
    "dots": 167
  },
  {
    "canto": 5,
    "lineStart": 46,
    "lineEnd": 72,
    "circle": 2,
    "shortDescript": "Ladies and Knights of Old",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 12,
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 2,
    "radiusStart": 4,
    "ychange": 0,
    "HSLlightHigh": 0.5,
    "HSLlightLow": 0.2,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 0.5,
    "thetaSpread": 0.02,
    "thetaStart": 0.5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.5,
    "dots": 12
  },
  {
    "canto": 5,
    "lineStart": 73,
    "lineEnd": 87,
    "circle": 2,
    "shortDescript": "Francesca and Paolo",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 2,
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 2,
    "radiusStart": 4,
    "ychange": 0,
    "HSLlightHigh": 0.3,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 0.02,
    "thetaStart": 0.25,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 2
  },
  {
    "canto": 6,
    "lineStart": 13,
    "lineEnd": 33,
    "circle": 3,
    "shortDescript": "Cerberus",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0.3,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 4.5,
    "thetaSpread": 0,
    "thetaStart": 4.5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 1
  },
  {
    "canto": 6,
    "lineStart": 34,
    "lineEnd": 36,
    "circle": 3,
    "shortDescript": "Souls (The Gluttons)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 5,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 4,
    "thetaStart": 6,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 88
  },
  {
    "canto": 6,
    "lineStart": 37,
    "lineEnd": 57,
    "circle": 3,
    "shortDescript": "Ciacco",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 2,
    "radiusStart": 9,
    "ychange": 0,
    "HSLlightHigh": 0.5,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 0.02,
    "thetaStart": 4,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 1
  },
  {
    "canto": 7,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 4,
    "shortDescript": "Plutus",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0.3,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 2.7,
    "thetaSpread": 0,
    "thetaStart": 2.7,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 1
  },
  {
    "canto": 7,
    "lineStart": 16,
    "lineEnd": 36,
    "circle": 4,
    "shortDescript": "Soul (Avaricious and Prodigal)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 6,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.45,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 4,
    "thetaStart": 4.3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 148
  },
  {
    "canto": 7,
    "lineStart": 109,
    "lineEnd": 117,
    "circle": 5,
    "shortDescript": "Souls in the Bog of Styx",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 1,
    "radiusStart": 2,
    "ychange": 0,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 4,
    "thetaStart": 3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 72
  },
  {
    "canto": 7,
    "lineStart": 118,
    "lineEnd": 130,
    "circle": 5,
    "shortDescript": "Souls under Styx",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 5,
    "radiusStart": 4,
    "ychange": 0,
    "HSLlightHigh": 0.15,
    "HSLlightLow": 0.1,
    "HSLsat": 0.35,
    "HSLhue": 0.72,
    "danteTheta": 1.2,
    "thetaSpread": 4,
    "thetaStart": 3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 97
  },
  {
    "canto": 8,
    "lineStart": 13,
    "lineEnd": 24,
    "circle": 5,
    "shortDescript": "Phlegyas",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 7,
    "ychange": 1,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 0.9,
    "thetaSpread": 0,
    "thetaStart": 0.9,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.7,
    "dots": 1
  },
  {
    "canto": 8,
    "lineStart": 31,
    "lineEnd": 63,
    "circle": 5,
    "shortDescript": "Flippo Argenti",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 9,
    "ychange": 0.5,
    "HSLlightHigh": 0.35,
    "HSLlightLow": 0,
    "HSLsat": 0.35,
    "HSLhue": 0.72,
    "danteTheta": 0.9,
    "thetaSpread": 0,
    "thetaStart": 0.91,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 1
  },
  {
    "canto": 8,
    "lineStart": 82,
    "lineEnd": 93,
    "circle": 6,
    "shortDescript": "The Wall of Dis",
    "motion": 0,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demons",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 3,
    "radiusStart": -1,
    "ychange": 5,
    "HSLlightHigh": 0.25,
    "HSLlightLow": 0.1,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 0.9,
    "thetaSpread": 1.1,
    "thetaStart": 1.55,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.45,
    "dots": 99
  },
  {
    "canto": 9,
    "lineStart": 34,
    "lineEnd": 51,
    "circle": 6,
    "shortDescript": "The Furies",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons",
    "objectNumber": 3,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": "Atop the wall",
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 9,
    "lineStart": 85,
    "lineEnd": 99,
    "circle": 6,
    "shortDescript": "The Messenger",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Angel",
    "objectNumber": 1,
    "distribution": 0,
    "rows": "Easter Egg",
    "radiusEnd": "(Blue White)",
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 9,
    "lineStart": 118,
    "lineEnd": 133,
    "circle": 6,
    "shortDescript": "Souls in Tombs (Heritics)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 3,
    "radiusStart": 1,
    "ychange": 0,
    "HSLlightHigh": 0.48,
    "HSLlightLow": 0.4,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.2,
    "thetaSpread": 3,
    "thetaStart": 2.5,
    "thetaGapStart": 1.65,
    "thetaGapEnd": 1.15,
    "dotSize": 0.7,
    "dots": 63
  },
  {
    "canto": 10,
    "lineStart": 22,
    "lineEnd": 51,
    "circle": 6,
    "shortDescript": "Farinata",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 3,
    "ychange": 0,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.3,
    "thetaSpread": 0,
    "thetaStart": 1.3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.85,
    "dots": 1
  },
  {
    "canto": 10,
    "lineStart": 52,
    "lineEnd": 72,
    "circle": 6,
    "shortDescript": "Cavalcante (in the same Tomb)",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 3,
    "ychange": 0.5,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.3,
    "thetaSpread": 0,
    "thetaStart": 1.33,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.35,
    "dots": 1
  },
  {
    "canto": 10,
    "lineStart": 115,
    "lineEnd": 123,
    "circle": 6,
    "shortDescript": "Other Souls in the Tomb",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "rows",
    "rows": 2,
    "radiusEnd": 1,
    "radiusStart": 2.7,
    "ychange": 0,
    "HSLlightHigh": 0.4,
    "HSLlightLow": 0.3,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 1.3,
    "thetaSpread": 0.02,
    "thetaStart": 1.5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.3,
    "dots": 14
  },
  {
    "canto": 11,
    "lineStart": 1,
    "lineEnd": 15,
    "circle": 6,
    "shortDescript": "Tomb of Pope Anastasius",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Soul",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 6,
    "ychange": 0,
    "HSLlightHigh": 0.46,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.11,
    "danteTheta": 0.8,
    "thetaSpread": 0,
    "thetaStart": 0.8,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.75,
    "dots": 1
  },
  {
    "canto": 12,
    "lineStart": 13,
    "lineEnd": 27,
    "circle": 7,
    "shortDescript": "The Minotaur",
    "motion": 1,
    "threshold": 1,
    "object": 1,
    "speech": 0,
    "objectType": "Demon",
    "objectNumber": 1,
    "distribution": "rows",
    "rows": 1,
    "radiusEnd": 0,
    "radiusStart": 0.1,
    "ychange": 0,
    "HSLlightHigh": 0.3,
    "HSLlightLow": 0,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 2.7,
    "thetaSpread": 0,
    "thetaStart": 0.5,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.6,
    "dots": 1
  },
  {
    "canto": 12,
    "lineStart": 55,
    "lineEnd": 66,
    "circle": 7,
    "shortDescript": "The Centaurs",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 1,
    "radiusEnd": 1,
    "radiusStart": 1,
    "ychange": 0,
    "HSLlightHigh": 0.26,
    "HSLlightLow": 0.12,
    "HSLsat": 1,
    "HSLhue": 0.02,
    "danteTheta": 6,
    "thetaSpread": 4,
    "thetaStart": 1,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.5,
    "dots": 63
  },
  {
    "canto": 12,
    "lineStart": 67,
    "lineEnd": 75,
    "circle": 7,
    "shortDescript": "Nessus, Chiron, Pholus (Centaurs)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Demons",
    "objectNumber": 3,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 12,
    "lineStart": 103,
    "lineEnd": 114,
    "circle": 7,
    "shortDescript": "Souls in River (Violence to Others)",
    "motion": 1,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": 4,
    "distribution": 0,
    "rows": 0,
    "radiusEnd": 0,
    "radiusStart": 0,
    "ychange": 0,
    "HSLlightHigh": 0,
    "HSLlightLow": 0,
    "HSLsat": 0,
    "HSLhue": 0,
    "danteTheta": 0,
    "thetaSpread": 0,
    "thetaStart": 0,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0,
    "dots": 0
  },
  {
    "canto": 12,
    "lineStart": 115,
    "lineEnd": 117,
    "circle": 7,
    "shortDescript": "River up to their heads",
    "motion": 0,
    "threshold": 0,
    "object": 1,
    "speech": 0,
    "objectType": "Souls",
    "objectNumber": "m",
    "distribution": "scatter",
    "rows": 2,
    "radiusEnd": 3,
    "radiusStart": 2,
    "ychange": 0,
    "HSLlightHigh": 0.15,
    "HSLlightLow": 0.25,
    "HSLsat": 0.89,
    "HSLhue": 0.1,
    "danteTheta": 1.2,
    "thetaSpread": 6,
    "thetaStart": 3,
    "thetaGapStart": 0,
    "thetaGapEnd": 0,
    "dotSize": 0.4,
    "dots": 97
  }
];